############################################
###       APPLICATION PARAMETERS         ###
############################################

# Address and port where the http webserver listening (0.0.0.0 denotes all available IP addresses)
server.address=0.0.0.0
server.port=6767

service.registry.address=127.0.0.1
service.registry.port=8443

############################################
###          CUSTOM PARAMETERS           ###
############################################

# Address to register into Service Registry with
domain.name=127.0.0.1

# The name of the system. If system uses X.509 certificate this should be consistent with the first part of the Common Name in the certificate.
system.name=DataSaver

# Method to authenticate service requester systems
authentication.policy=declared

# Enable/disable the requirement for authorization control (when ConsumerAuthorization Arrowhead Core System is deployed to the local cloud)
enable.authorization=false

# Show all request/response in debug log
log.all.request.and.response=false

# Path of the folder where the files should be saved
save.location=C:/Users/sga/Documents/PythonDataModelTranslation/final_result

############################################
###             SSL MODE                 ###
############################################

# configure secure mode

# Set this to false to disable https mode
server.ssl.enabled=false

server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:certificate/WrapperForPythonDataModelTranslator.p12
server.ssl.key-store-password=123456
server.ssl.key-alias=WrapperForPythonDataModelTranslator.TestCloud.Company.arrowhead.eu
server.ssl.key-password=123456
# Set to "need" in case of CERTIFICATE authentication policy
server.ssl.client-auth=none
server.ssl.trust-store-type=PKCS12
server.ssl.trust-store=classpath:certificate/truststore.p12
server.ssl.trust-store-password=123456

# If true, http client does not check whether the hostname is match one of the server's SAN in its certificate
disable.hostname.verifier=false